<?php
/**
 * @copyright Copyright 2003-2022 Zen Cart Development Team
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 */

namespace Tests\Support;

use App\Models\Configuration;
use App\Models\ProductTypeLayout;
use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\TestResult;
use Tests\Support\Traits\ConfigurationSettingsConcerns;
use Tests\Support\Traits\CustomerAccountConcerns;
use Tests\Support\Traits\DatabaseConcerns;
use Tests\Support\Traits\GeneralConcerns;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Tests\Support\Traits\LogFileConcerns;

/**
 *
 */
abstract class zcDatabaseTestCase extends TestCase
{
    use DatabaseConcerns, GeneralConcerns, CustomerAccountConcerns, ConfigurationSettingsConcerns, LogFileConcerns;

    /**
     * @return void
     *
     * set some defines where necessary
     */
    public static function setUpBeforeClass(): void
    {
        if (!defined('TESTCWD')) {
            define('TESTCWD', realpath(__DIR__ . '/../') . '/');
        }
        if (!defined('ROOTCWD')) {
            define('ROOTCWD', realpath(__DIR__ . '/../../../') . '/');
        }
        if (!defined('TEXT_PROGRESS_FINISHED')) {
            define('TEXT_PROGRESS_FINISHED', '');
        }

        parent::setUpBeforeClass();
        self::loadConfigureFile('store');
        self::loadMigrationAndSeeders();
        if (!defined('TABLE_ADDRESS_BOOK')) {
            require DIR_FS_CATALOG . 'includes/database_tables.php';
        }
        self::removeLogFiles();
        self::loadConfigurationValues();
    }

    public static function loadConfigurationValues()
    {
        if (defined('SHOW_PRODUCT_INFO_MODEL')) {
            return;
        }
        $config = new Configuration();
        $config->loadConfigSettings();
        $config = new ProductTypeLayout();
        $config->loadConfigSettings();

    }
    public function tearDown(): void
    {
        global $db;
        //$db->close();
        if (file_exists(ROOTCWD . 'progress.json')) {
            unlink(ROOTCWD . 'progress.json');
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    protected static function removeLogFiles()
    {
        $pattern = 'myDEBUG*';
        $directory = ROOTCWD . 'logs/';
        $files = glob($directory . $pattern);
        foreach ($files as $file) {
            if (is_file($file)) {
                self::moveLogFileForArtifacts($file);
                unlink($file);
            }
        }
    }

    protected static function moveLogFileForArtifacts($file)
    {
        $context = 'store';
        if (str_starts_with(basename($file), 'myDEBUG-adm')) {
            $context = 'admin';
        }
        if (!is_dir(ROOTCWD . 'not_for_release/testFramework/logs/console/' . $context . '/')) {
            mkdir(ROOTCWD . 'not_for_release/testFramework/logs/console/' . $context . '/');
        }
        copy($file,  ROOTCWD . 'not_for_release/testFramework/logs/console/' . $context . '/' . basename($file));
    }

}
