<?php
/**
 * @copyright Copyright 2003-2022 Zen Cart Development Team
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 */

namespace Tests\Support;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\TestResult;
use Tests\Support\Traits\DatabaseConcerns;
use Tests\Support\Traits\GeneralConcerns;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 *
 */
abstract class zcFeatureTestCase extends WebTestCase
{
    use DatabaseConcerns, GeneralConcerns;


    /**
     * @param TestResult|null $result
     * @return TestResult
     *
     * This allows us to run in full isolation mode including
     * classes, functions, and defined statements
     */
    public function run(TestResult $result = null): TestResult
    {
        $this->setPreserveGlobalState(false);
        return parent::run($result);
    }

    /**
     * @return void
     *
     * set some defines where necessary
     */
    public function setUp(): void
    {
        //echo 'Detected User = ' . $this->detectUser() ."\n";
        if (!defined('ZENCART_TESTFRAMEWORK_RUNNING')) {
            define('ZENCART_TESTFRAMEWORK_RUNNING', true);
        }
        if (!defined('TESTCWD')) {
            define('TESTCWD', realpath(__DIR__ . '/../') . '/');
        }
        if (!defined('ROOTCWD')) {
            define('ROOTCWD', realpath(__DIR__ . '/../../../') . '/');
        }

        $this->loadConfigureFile($this->context);
        $this->loadMigrationAndSeeders();
        $this->createHttpBrowser();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
